collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.506383
color:
  saturation: 0.1531915
  brandStrength: 0.5425532
  lightness: 0.1148936
  brandColors:
    - '#FFFFFF'
    - '#8C0000'
    - '#CE9292'
    - '#E1BDBD'
    - '#BA6565'
  rhythmicContrast: 0.5723404
layout_spectrum: 0.3510638
name: 24HourRestoration.com
